# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commons/response.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message 'nest.commons.GenericResponse' do
    optional :success, :bool, 1
    optional :info, :string, 2
  end
end

module Nest
  module Commons
    GenericResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup('nest.commons.GenericResponse').msgclass
  end
end
