# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: test.proto for package 'testgrpc'

require 'grpc'
require_relative 'test_pb'

module Testgrpc
  module TestgrpcService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'testgrpc.TestgrpcService'

      rpc :hellogrpc, HelloRequest, HelloResponse
    end

    Stub = Service.rpc_stub_class
  end
end
