# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "testgrpc.HelloRequest" do
    optional :req_message, :string, 1
  end
  add_message "testgrpc.HelloResponse" do
    optional :res_message, :string, 1
  end
  add_message "testgrpc.CustomError" do
    optional :custom, :string, 1
  end
end

module Testgrpc
  HelloRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("testgrpc.HelloRequest").msgclass
  HelloResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("testgrpc.HelloResponse").msgclass
  CustomError = Google::Protobuf::DescriptorPool.generated_pool.lookup("testgrpc.CustomError").msgclass
end
